export const NEPAL_DISTRICTS = [
  'Achham',
  'Arghakhanchi',
  'Baglung',
  'Baitadi',
  'Bajhang',
  'Bajura',
  'Banke',
  'Bara',
  'Bardiya',
  'Bhojpur',
  'Chitwan',
  'Dadeldhura',
  'Dailekh',
  'Dang',
  'Darchula',
  'Dhading',
  'Dhankuta',
  'Dhanusha',
  'Dolakha',
  'Dolpa',
  'Doti',
  'Gorkha',
  'Gulmi',
  'Humla',
  'Ilam',
  'Jajarkot',
  'Jhapa',
  'Jumla',
  'Kailali',
  'Kalikot',
  'Kanchanpur',
  'Kapilvastu',
  'Kaski',
  'Kathmandu',
  'Kavrepalanchok',
  'Khotang',
  'Lalitpur',
  'Lamjung',
  'Mahottari',
  'Makwanpur',
  'Manang',
  'Morang',
  'Mugu',
  'Mustang',
  'Myagdi',
  'Nawalparasi West',
  'Nawalpur',
  'Nuwakot',
  'Okhaldhunga',
  'Palpa',
  'Panchthar',
  'Parbat',
  'Parsa',
  'Pyuthan',
  'Ramechhap',
  'Rasuwa',
  'Rautahat',
  'Rolpa',
  'Rukum East',
  'Rukum West',
  'Rupandehi',
  'Salyan',
  'Sankhuwasabha',
  'Saptari',
  'Sarlahi',
  'Sindhuli',
  'Sindhupalchok',
  'Siraha',
  'Solukhumbu',
  'Sunsari',
  'Surkhet',
  'Syangja',
  'Tanahun',
  'Taplejung',
  'Terhathum',
  'Udayapur',
];

export const DISTRICT_ALIASES = {
  // common misspellings / legacy values
  ilum: 'Ilam',
  illam: 'Ilam',
  dhanusa: 'Dhanusha',
  nawalparasi: 'Nawalparasi West',
  'nawalparasi east': 'Nawalpur',
  rukum: 'Rukum West',
  sindhupalachok: 'Sindhupalchok',
  kavrepalanchowk: 'Kavrepalanchok',
  kavre: 'Kavrepalanchok',
  bhaktapur: 'Bhaktapur', // not in 77-district split but keep for legacy
  nuwakott: 'Nuwakot',
  chitawan: 'Chitwan',
  solukhimbu: 'Solukhumbu',
};

export const normalizeDistrict = (raw) => {
  if (!raw) return null;
  const trimmed = raw.trim();
  const lower = trimmed.toLowerCase();
  if (DISTRICT_ALIASES[lower]) return DISTRICT_ALIASES[lower];
  const canonical = NEPAL_DISTRICTS.find((d) => d.toLowerCase() === lower);
  return canonical || trimmed;
};
