import Joi from 'joi';

export const candidateSchema = Joi.object({
  fullName: Joi.string().trim().min(2).max(100).required(),
  fullNameNepali: Joi.string().trim().max(100).optional(),
  dateOfBirth: Joi.date().iso().required(),
  gender: Joi.string().valid('male', 'female', 'other').required(),
  nationalIdNumber: Joi.string().trim().min(2).max(30).required(),
  phone: Joi.string().trim().min(7).max(20).required(),
  alternatePhone: Joi.string().trim().min(7).max(20).optional(),
  email: Joi.string().email().optional(),
  permanentProvince: Joi.string().optional(),
  permanentDistrict: Joi.string().optional(),
  permanentMunicipality: Joi.string().optional(),
  permanentWardNo: Joi.string().optional(),
  temporaryAddress: Joi.string().optional(),
  education: Joi.string().valid('illiterate', 'primary', 'slc', 'plus2', 'bachelor', 'master').optional(),
  skills: Joi.array().items(Joi.string()).optional(),
  languagesKnown: Joi.array().items(Joi.string()).optional(),
  workExperienceYears: Joi.number().min(0).max(50).optional(),
  previousCountry: Joi.string().optional(),
  desiredCountry: Joi.string().optional(),
  desiredJobCategory: Joi.string().optional(),
  referredBy: Joi.string().optional(),
  agentId: Joi.string().optional(),
  serviceFeeAgreed: Joi.number().min(0).optional(),
  serviceFeeReceived: Joi.number().min(0).optional()
});

export const candidateUpdateSchema = Joi.object({
  fullName: Joi.string().trim().min(2).max(100),
  fullNameNepali: Joi.string().trim().max(100),
  dateOfBirth: Joi.date().iso(),
  gender: Joi.string().valid('male', 'female', 'other'),
  nationalIdNumber: Joi.string().trim().min(2).max(30),
  phone: Joi.string().trim().min(7).max(20),
  alternatePhone: Joi.string().trim().min(7).max(20),
  email: Joi.string().email(),
  permanentProvince: Joi.string(),
  permanentDistrict: Joi.string(),
  permanentMunicipality: Joi.string(),
  permanentWardNo: Joi.string(),
  temporaryAddress: Joi.string(),
  education: Joi.string().valid('illiterate', 'primary', 'slc', 'plus2', 'bachelor', 'master'),
  skills: Joi.array().items(Joi.string()),
  languagesKnown: Joi.array().items(Joi.string()),
  workExperienceYears: Joi.number().min(0).max(50),
  previousCountry: Joi.string(),
  desiredCountry: Joi.string(),
  desiredJobCategory: Joi.string(),
  referredBy: Joi.string(),
  agentId: Joi.string(),
  serviceFeeAgreed: Joi.number().min(0),
  serviceFeeReceived: Joi.number().min(0)
});